# Generated by Django 4.2.2 on 2023-06-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='days',
            field=models.CharField(default=2, max_length=50),
        ),
    ]
