# Generated by Django 4.2.2 on 2023-06-27 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='image',
        ),
        migrations.CreateModel(
            name='ImageAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads/attraction')),
                ('model', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='attraction.attraction')),
            ],
        ),
    ]
