# Generated by Django 4.2.2 on 2023-06-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0002_remove_attraction_image_imageattraction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageAttraction',
            new_name='Image_Attraction',
        ),
    ]
