# Generated by Django 4.2.2 on 2023-06-26 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_heb', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('descript', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads/hebergement')),
                ('model', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='hebergement.hebergement')),
            ],
        ),
    ]
