# Generated by Django 4.2.2 on 2023-06-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hebergement',
            old_name='descript',
            new_name='localisation',
        ),
        migrations.RemoveField(
            model_name='hebergement',
            name='ville',
        ),
        migrations.AddField(
            model_name='hebergement',
            name='contact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='nb_star',
            field=models.IntegerField(default=1),
        ),
    ]
