# Generated by Django 4.2.2 on 2023-06-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0002_rename_descript_hebergement_localisation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Images_Hebergement',
        ),
    ]
